best_params:
  n_estimators: 100
  max_depth: 8           # Reduced from 10
  max_features: "sqrt"
  min_samples_split: 15   # Increased from 10
  min_samples_leaf: 8     # Increased from 4
  random_state: 42
  n_jobs: -1
  bootstrap: true
  max_samples: 0.8       # Use only 80% of data for each tree